### PR TITLE
Fixing package.json config loading & dependencies

### PR DESCRIPTION
**Pull request by iskrisis**
This fixes settings inside package.json which couldn't work because `var configFile = require(appRoot + '/rploy.config.js');` was loading the config every time.

Also i think the `app-root-path` is unnecessary since the config should live besides `package.json` the `path.resolve('./rploy.config.js')` should be enough. 'app-root-path` was actually giving me path to the package when developing locally which is probably it's purpose but not what we actually want?

I think this will need change in docs because 
```js
module.exports = () => {
  return {
    source: 'public/',
    destination: "user@ip:/var/www/public/",
  }
}
``` 
wont work. I am not sure why returning function for config was required.
This is enough?
```js
module.exports =  {
    source: 'public/',
    destination: "user@ip:/var/www/public/",
}
```

Note: i've used `fs.existsSync` just because with configs i don't think there is benefit with `async` (especially since there would be `await` slapped in front of it and the syntax is simpler. But if there is some benefit i am not aware of i guess it can be rewritten to be async.

### CODE REVIEW

**Comment by moevbiz** [comment]
> I am not sure why returning function for config was required

because https://github.com/jongacnik/rploy/issues/5#issuecomment-947856987

**Comment by iskrisis** [comment]
@moevbiz i still dont uderstand why it was required to use closure? 

anyway can you test the PR? the rploy.config.js works correctly.

**Comment by moevbiz** [comment]
not 100% sure if what i am saying is true, but by using an object literal instead of closure it is not possible anymore to use any logic aside from like string concatenation or basic math. as i said, i tried to follow the plugin authors' idea of being able to use logic in a `.js` file – even though i currently don't have a use case for it, i can imagine a possible scenario where you might want to import settings from i.e a `.env` file.

i just tested your code however and it works fine for my use case. i believe it should be up to @jongacnik to decide whether a `.js` file abstraction of the `package.json` method is fine instead. but i also feel bad for fucking up the package json method with my contribution so idk, up to you i guess – maybe update the section in the docs accordingly though

**Comment by iskrisis** [comment]
Its all fine. Both of the usages are valid no question about that. 

You can use any logic you want inside the config js file. The absence closure doesnt change that. Only reason for the closure would be if there would be anything passed to the function and i dont think there is situation where this would make sense. Its really similar to any other config of this type (tailwind, rollup, webpack etc).

I am just trying to keep things simple.

**Comment by iskrisis** [comment]
@jongacnik gentle bump. Could you maybe merge this? Or have all of you started to use separate file suddenly?

**Comment by jongacnik** [comment]
Hey thanks for you patience (and help!) here. Been really busy with other projects. Just merged things, tweaked the readme, and republished to npm. Hopefully this is working for everyone's needs now 🤞

**Comment by iskrisis** [comment]
Thanks @jongacnik !!! Cheers

**Pull request merged**
